server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/resourcedb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:pguser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pgpassword}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

song-service.url=${SONG_SERVICE_URL:http://localhost:8082}